spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:

      # This is the CROSS Configuration to allow only access from Elphie FE URL 
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000/"
            allowedMethods:
            - GET,POST,PUT,DELETE

      # This are the Routes declaration to the Services
      routes:

      # Users Service Route
      - id: USERS-SERVICE
        uri: http://localhost:9000
        predicates:
        - Path=/users/**
        - Method=GET,POST,PUT,DELETE

      # Savings Service Route
      - id: SAVINGS-SERVICE
        uri: http://localhost:9001
        predicates:
        - Path=/savings/**
        - Method=GET,POST,PUT,DELETE

      # Accounts Service Route
      - id: ACCOUNTS-SERVICE
        uri: http://localhost:9002
        predicates:
        - Path=/accounts/**,/transactions/**
        - Method=GET,POST,PUT,DELETE